<?php
include_once __DIR__ . "/../parts/header.phtml";
?>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">SimpleBlog</div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>Blog</li>
                    <li>Admin</li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <form class="form-edit" method="POST">
            <h2 class="form-edit-heading">Edit Post</h2>
            <label for="title">Title</label>
            <input type="text" name="title" id="title" class="form-control" placeholder="Title" required="" autofocus="" value="<?php echo $post->title ?>">
            <label for="text">Text</label>
            <textarea id="text" name="text" class="form-control"><?php echo $post->text; ?></textarea>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
        </form>
    </div>

<?php
include_once __DIR__ . "/../parts/footer.phtml";
?>