<?php
include_once __DIR__ . "/../parts/header.phtml";
?>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">SimpleBlog</div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>Blog</li>
                    <li>Admin</li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <form class="form-signin">
            <h2 class="form-signin-heading">Login</h2>
            <label for="inputEmail" class="sr-only">Email address</label>
            <input type="text" id="user" class="form-control" placeholder="User" required="" autofocus="">
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="password" class="form-control" placeholder="Password" required="">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
    </div>

<?php
include_once __DIR__ . "/../parts/footer.phtml";
?>