<?php
include_once __DIR__ . "/../parts/header.phtml";
?>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">SimpleBlog</div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>Blog</li>
                <li>Admin</li>
            </ul>
        </div>
    </div>
</nav>

    <div class="container-fluid">
            <div class="starter-template ">
                <h1><?php echo $post->title ?></h1>
                <h3><?php echo $post->date ?></h3>
                <p class="lead"><?php echo $post->text; ?></p>
            </div>
    </div>

<?php
include_once __DIR__ . "/../parts/footer.phtml";
?>